# Generated by Django 3.2.5 on 2021-08-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
