# Generated by Django 3.2.7 on 2021-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='nombre',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
