# Generated by Django 3.2.7 on 2021-10-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurante.sede'),
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.sede')),
            ],
        ),
    ]
