# Generated by Django 3.2.7 on 2021-10-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_auto_20211007_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='product_images/default.png', upload_to='product_images/'),
        ),
    ]
